
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "monthly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/react"
    schedule:
      interval: "monthly"
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`.
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"