
version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/react"
    schedule:
      interval: "weekly"
