image:
  file: .gitpod.Dockerfile

ports:
  - port: 5050
    onOpen: open-browser
  - port: 5173
    onOpen: open-browser

tasks:
  - name: python
    before: |
      cp -n python/defaults/* python/work/
    init: |
      pip install --upgrade pip
      pip install -r python/requirements.txt

  - name: react
    before: |
      cd $GITPOD_REPO_ROOTS/react/public
      ln -s ../../python/work/web web || true
    init: |
      cd $GITPOD_REPO_ROOTS/react
      npm install
      cd $GITPOD_REPO_ROOTS

gitConfig:
  alias.st: status -s
  alias.co: checkout
  alias.hist: log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short --no-merges
  rebase.autostash: "true"
  pull.autostash: "true"

vscode:
  extensions:
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - ms-python.flake8
    - ms-python.isort
    - ms-python.pylint
    - ms-python.python
    # not found in OPen VSX
    # - ms-python.autopep8
    # - ms-python.vscode-pylance
    # - VisualStudioExptTeam.vscodeintellicode
    # - GitHub.vscode-pull-request-github
