image:
  file: .gitpod.Dockerfile

ports:
  - port: 5050
    onOpen: open-browser
  - port: 5173
    onOpen: open-browser

tasks:
  - name: python
    before: |
      cp -n python/defaults/* python/work/
    init: |
      pip install --upgrade pip
      pip install -U -r python/requirements.txt -r python/requirements-devel.txt

  - name: react
    before: |
      cd $GITPOD_REPO_ROOTS/react/public
      ln -s ../../python/work/web web || true
    init: |
      cd $GITPOD_REPO_ROOTS/react
      npm install && npm run build
      cd $GITPOD_REPO_ROOTS

gitConfig:
  alias.st: status -s
  alias.co: checkout
  alias.hist: log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short --no-merges
  rebase.autostash: "true"
  pull.autostash: "true"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - charliermarsh.ruff
    - mhutchie.git-graph
    - mk12.better-git-line-blame
    - ms-python.debugpy
    - ms-python.python
    - shd101wyy.markdown-preview-enhanced
#    - ms-python.vscode-pylance
