# https://docs.astral.sh/ruff/settings/

line-length = 128
src = ["src", "test", "simulator", "ignore"]
# namespace-packages = ["airflow/providers"]

[format]
quote-style = "single"
skip-magic-trailing-comma = true

# [project]
# requires-python = ">=3.9"
# target-version = "py39"

[lint]
# Skip unused variable rules (`F841`).
# extend-ignore = ["F841"]

[lint.flake8-annotations]
suppress-dummy-args = true
# suppress-none-returning = true

[lint.isort]
combine-as-imports = true
# force-sort-within-sections = true
split-on-trailing-comma = false
